### ISSUE TITLE
`login` command fails

### ISSUE THREAD

**Issue by dbosk** [dbosk/canvaslms#74]
```
$ canvaslms login
Traceback (most recent call last):
  File "/home/dbosk/.local/bin/canvaslms", line 8, in <module>
    sys.exit(main())
  File "/home/dbosk/.local/lib/python3.10/site-packages/canvaslms/cli/__init__.py", line 90, in main
    canvas = Canvas(hostname, token)
  File "/home/dbosk/.local/lib/python3.10/site-packages/canvasapi/canvas.py", line 32, in __init__
    if "api/v1" in base_url:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by dbosk** [comment]
Fixed!
